// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final fluttiumLauncherBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": ".{{runner_id}}_launcher.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnt7e3Byb2plY3RfbmFtZX19fS97e3ttYWluX2VudHJ5fX19JyBhcyBhcHA7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwoKaW1wb3J0ICdwYWNrYWdlOmZsdXR0aXVtX3Rlc3RfcnVubmVyL2ZsdXR0aXVtX3Rlc3RfcnVubmVyLmRhcnQnIGFzIHRlc3RfcnVubmVyOwoKdm9pZCBtYWluKCkgYXN5bmMgewogIGZpbmFsIGJpbmRpbmcgPSBXaWRnZXRzRmx1dHRlckJpbmRpbmcuZW5zdXJlSW5pdGlhbGl6ZWQoKQogICAgLi5zZXRTZW1hbnRpY3NFbmFibGVkKHRydWUpOwoKICBhd2FpdCBGdXR1cmUoYXBwLm1haW4pOwogIGF3YWl0IGJpbmRpbmcuZW5kT2ZGcmFtZTsKICBhd2FpdCB0ZXN0X3J1bm5lci5ydW4oYmluZGluZyk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [
    {
      "path": "post_gen.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmlvJzsKCmltcG9ydCAncGFja2FnZTptYXNvbi9tYXNvbi5kYXJ0JzsKCnR5cGVkZWYgUHJvY2Vzc1J1bm5lciA9IEZ1dHVyZTxQcm9jZXNzUmVzdWx0PiBGdW5jdGlvbigKICBTdHJpbmcgZXhlY3V0YWJsZSwKICBMaXN0PFN0cmluZz4gYXJndW1lbnRzLCB7CiAgU3RyaW5nIHdvcmtpbmdEaXJlY3RvcnksCiAgYm9vbCBydW5JblNoZWxsLAp9KTsKCi8vIGNvdmVyYWdlOmlnbm9yZS1zdGFydApGdXR1cmU8dm9pZD4gcnVuKEhvb2tDb250ZXh0IGNvbnRleHQpID0+IHBvc3RHZW4oY29udGV4dCk7Ci8vIGNvdmVyYWdlOmlnbm9yZS1lbmQKCkZ1dHVyZTx2b2lkPiBwb3N0R2VuKAogIEhvb2tDb250ZXh0IGNvbnRleHQsIHsKICBEaXJlY3Rvcnk/IGRpcmVjdG9yeSwKICBQcm9jZXNzUnVubmVyIHJ1blByb2Nlc3MgPSBQcm9jZXNzLnJ1biwKfSkgYXN5bmMgewogIGZpbmFsIHVuaW5zdGFsbGluZ1Rlc3RSdW5uZXIgPSBjb250ZXh0LmxvZ2dlci5wcm9ncmVzcygKICAgICdVbmluc3RhbGxpbmcgdGVzdCBydW5uZXInLAogICk7CgogIGF3YWl0IHJ1blByb2Nlc3MoCiAgICAnZmx1dHRlcicsCiAgICBbJ3B1YicsICdyZW1vdmUnLCAnZmx1dHRpdW1fdGVzdF9ydW5uZXInXSwKICAgIHJ1bkluU2hlbGw6IHRydWUsCiAgICB3b3JraW5nRGlyZWN0b3J5OiBEaXJlY3RvcnkuY3VycmVudC5wYXRoLAogICk7CgogIHVuaW5zdGFsbGluZ1Rlc3RSdW5uZXIuY29tcGxldGUoKTsKfQo=",
      "type": "text"
    },
    {
      "path": "pre_gen.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmlvJzsKCmltcG9ydCAncGFja2FnZTptYXNvbi9tYXNvbi5kYXJ0JzsKCnR5cGVkZWYgUHJvY2Vzc1J1bm5lciA9IEZ1dHVyZTxQcm9jZXNzUmVzdWx0PiBGdW5jdGlvbigKICBTdHJpbmcgZXhlY3V0YWJsZSwKICBMaXN0PFN0cmluZz4gYXJndW1lbnRzLCB7CiAgU3RyaW5nIHdvcmtpbmdEaXJlY3RvcnksCiAgYm9vbCBydW5JblNoZWxsLAp9KTsKCi8vIGNvdmVyYWdlOmlnbm9yZS1zdGFydApGdXR1cmU8dm9pZD4gcnVuKEhvb2tDb250ZXh0IGNvbnRleHQpID0+IHByZUdlbihjb250ZXh0KTsKLy8gY292ZXJhZ2U6aWdub3JlLWVuZAoKRnV0dXJlPHZvaWQ+IHByZUdlbigKICBIb29rQ29udGV4dCBjb250ZXh0LCB7CiAgRGlyZWN0b3J5PyBkaXJlY3RvcnksCiAgUHJvY2Vzc1J1bm5lciBydW5Qcm9jZXNzID0gUHJvY2Vzcy5ydW4sCn0pIGFzeW5jIHsKICBmaW5hbCBpbnN0YWxsaW5nVGVzdFJ1bm5lciA9IGNvbnRleHQubG9nZ2VyLnByb2dyZXNzKAogICAgJ0luc3RhbGxpbmcgdGVzdCBydW5uZXInLAogICk7CgogIGF3YWl0IHJ1blByb2Nlc3MoCiAgICAnZmx1dHRlcicsCiAgICBbJ3B1YicsICdyZW1vdmUnLCAnZmx1dHRpdW1fdGVzdF9ydW5uZXInXSwKICAgIHJ1bkluU2hlbGw6IHRydWUsCiAgICB3b3JraW5nRGlyZWN0b3J5OiBEaXJlY3RvcnkuY3VycmVudC5wYXRoLAogICk7CgogIGF3YWl0IHJ1blByb2Nlc3MoCiAgICAnZmx1dHRlcicsCiAgICBbCiAgICAgICdwdWInLAogICAgICAnYWRkJywKICAgICAgJ2ZsdXR0aXVtX3Rlc3RfcnVubmVyJywKICAgICAgJy0tZGV2JywKICAgICAgJy0tcGF0aCcsCiAgICAgIGNvbnRleHQudmFyc1sncnVubmVyX3BhdGgnXSBhcyBTdHJpbmcsCiAgICBdLAogICAgcnVuSW5TaGVsbDogdHJ1ZSwKICAgIHdvcmtpbmdEaXJlY3Rvcnk6IERpcmVjdG9yeS5jdXJyZW50LnBhdGgsCiAgKTsKCiAgaW5zdGFsbGluZ1Rlc3RSdW5uZXIuY29tcGxldGUoKTsKfQo=",
      "type": "text"
    },
    {
      "path": "pubspec.yaml",
      "data":
          "bmFtZTogdGVzdF9ob29rcwoKZW52aXJvbm1lbnQ6CiAgc2RrOiAiPj0yLjE5LjAgPDMuMC4wIgoKZGVwZW5kZW5jaWVzOgogIG1hc29uOiAiPj0wLjEuMC1kZXYuNDIgPDAuMS4wIgogIG1vY2t0YWlsOiBeMC4zLjAKCmRldl9kZXBlbmRlbmNpZXM6CiAgdGVzdDogXjEuMTkuMgogIHZlcnlfZ29vZF9hbmFseXNpczogXjQuMC4wCg==",
      "type": "text"
    },
    {
      "path": "test/post_gen_test.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmlvJzsKCmltcG9ydCAncGFja2FnZTptYXNvbi9tYXNvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOm1vY2t0YWlsL21vY2t0YWlsLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6dGVzdC90ZXN0LmRhcnQnOwoKaW1wb3J0ICcuLi9wb3N0X2dlbi5kYXJ0JzsKCmNsYXNzIF9GYWtlSG9va0NvbnRleHQgZXh0ZW5kcyBGYWtlIGltcGxlbWVudHMgSG9va0NvbnRleHQgewogIF9GYWtlSG9va0NvbnRleHQoe0xvZ2dlcj8gbG9nZ2VyfSkgOiBfbG9nZ2VyID0gbG9nZ2VyID8/IF9Nb2NrTG9nZ2VyKCk7CgogIGZpbmFsIExvZ2dlciBfbG9nZ2VyOwoKICB2YXIgX3ZhcnMgPSA8U3RyaW5nLCBkeW5hbWljPnt9OwoKICBAb3ZlcnJpZGUKICBNYXA8U3RyaW5nLCBkeW5hbWljPiBnZXQgdmFycyA9PiBfdmFyczsKCiAgQG92ZXJyaWRlCiAgc2V0IHZhcnMoTWFwPFN0cmluZywgZHluYW1pYz4gdmFsdWUpID0+IF92YXJzID0gdmFsdWU7CgogIEBvdmVycmlkZQogIExvZ2dlciBnZXQgbG9nZ2VyID0+IF9sb2dnZXI7Cn0KCmNsYXNzIF9Nb2NrTG9nZ2VyIGV4dGVuZHMgTW9jayBpbXBsZW1lbnRzIExvZ2dlciB7fQoKY2xhc3MgX01vY2tQcm9ncmVzcyBleHRlbmRzIE1vY2sgaW1wbGVtZW50cyBQcm9ncmVzcyB7fQoKY2xhc3MgX01vY2tQcm9jZXNzUmVzdWx0IGV4dGVuZHMgTW9jayBpbXBsZW1lbnRzIFByb2Nlc3NSZXN1bHQge30KCnZvaWQgbWFpbigpIHsKICBncm91cCgncG9zdEdlbicsICgpIHsKICAgIGxhdGUgSG9va0NvbnRleHQgY29udGV4dDsKICAgIGxhdGUgTG9nZ2VyIGxvZ2dlcjsKICAgIGxhdGUgUHJvZ3Jlc3MgdW5pbnN0YWxsaW5nVGVzdFJ1bm5lcjsKCiAgICBzZXRVcCgoKSB7CiAgICAgIGxvZ2dlciA9IF9Nb2NrTG9nZ2VyKCk7CiAgICAgIGNvbnRleHQgPSBfRmFrZUhvb2tDb250ZXh0KGxvZ2dlcjogbG9nZ2VyKTsKICAgICAgdW5pbnN0YWxsaW5nVGVzdFJ1bm5lciA9IF9Nb2NrUHJvZ3Jlc3MoKTsKCiAgICAgIHdoZW4oKCkgPT4gbG9nZ2VyLnByb2dyZXNzKGFueSgpKSkudGhlblJldHVybih1bmluc3RhbGxpbmdUZXN0UnVubmVyKTsKICAgIH0pOwoKICAgIHRlc3QoJ3J1biBjb21wbGV0ZXMnLCAoKSB7CiAgICAgIGV4cGVjdChydW4oY29udGV4dCksIGNvbXBsZXRlcyk7CiAgICB9KTsKCiAgICB0ZXN0KCd1bmluc3RhbGxzIGZsdXR0aXVtX3Rlc3RfcnVubmVyIGNvcnJlY3RseScsICgpIGFzeW5jIHsKICAgICAgdmFyIHByb2Nlc3NSdW5uZXJDYWxsQ291bnQgPSAwOwoKICAgICAgZmluYWwgcmVzdWx0ID0gX01vY2tQcm9jZXNzUmVzdWx0KCk7CiAgICAgIGF3YWl0IHBvc3RHZW4oCiAgICAgICAgY29udGV4dCwKICAgICAgICBydW5Qcm9jZXNzOiAoCiAgICAgICAgICBleGVjdXRhYmxlLAogICAgICAgICAgYXJncywgewogICAgICAgICAgU3RyaW5nPyB3b3JraW5nRGlyZWN0b3J5LAogICAgICAgICAgYm9vbD8gcnVuSW5TaGVsbCwKICAgICAgICB9KSBhc3luYyB7CiAgICAgICAgICBwcm9jZXNzUnVubmVyQ2FsbENvdW50Kys7CiAgICAgICAgICBleHBlY3QoZXhlY3V0YWJsZSwgZXF1YWxzKCdmbHV0dGVyJykpOwogICAgICAgICAgZXhwZWN0KGFyZ3MsIGVxdWFscyhbJ3B1YicsICdyZW1vdmUnLCAnZmx1dHRpdW1fdGVzdF9ydW5uZXInXSkpOwogICAgICAgICAgZXhwZWN0KHdvcmtpbmdEaXJlY3RvcnksIGVxdWFscyhEaXJlY3RvcnkuY3VycmVudC5wYXRoKSk7CiAgICAgICAgICBleHBlY3QocnVuSW5TaGVsbCwgaXNUcnVlKTsKICAgICAgICAgIHJldHVybiByZXN1bHQ7CiAgICAgICAgfSwKICAgICAgKTsKCiAgICAgIGV4cGVjdChwcm9jZXNzUnVubmVyQ2FsbENvdW50LCBlcXVhbHMoMSkpOwogICAgICB2ZXJpZnkoCiAgICAgICAgKCkgPT4gbG9nZ2VyLnByb2dyZXNzKGFueSh0aGF0OiBlcXVhbHMoJ1VuaW5zdGFsbGluZyB0ZXN0IHJ1bm5lcicpKSksCiAgICAgICkuY2FsbGVkKDEpOwogICAgICB2ZXJpZnkoKCkgPT4gdW5pbnN0YWxsaW5nVGVzdFJ1bm5lci5jb21wbGV0ZSgpKS5jYWxsZWQoMSk7CiAgICB9KTsKICB9KTsKfQo=",
      "type": "text"
    },
    {
      "path": "test/pre_gen_test.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmlvJzsKCmltcG9ydCAncGFja2FnZTptYXNvbi9tYXNvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOm1vY2t0YWlsL21vY2t0YWlsLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6dGVzdC90ZXN0LmRhcnQnOwoKaW1wb3J0ICcuLi9wcmVfZ2VuLmRhcnQnOwoKY2xhc3MgX0Zha2VIb29rQ29udGV4dCBleHRlbmRzIEZha2UgaW1wbGVtZW50cyBIb29rQ29udGV4dCB7CiAgX0Zha2VIb29rQ29udGV4dCh7TG9nZ2VyPyBsb2dnZXJ9KSA6IF9sb2dnZXIgPSBsb2dnZXIgPz8gX01vY2tMb2dnZXIoKTsKCiAgZmluYWwgTG9nZ2VyIF9sb2dnZXI7CgogIHZhciBfdmFycyA9IDxTdHJpbmcsIGR5bmFtaWM+e307CgogIEBvdmVycmlkZQogIE1hcDxTdHJpbmcsIGR5bmFtaWM+IGdldCB2YXJzID0+IF92YXJzOwoKICBAb3ZlcnJpZGUKICBzZXQgdmFycyhNYXA8U3RyaW5nLCBkeW5hbWljPiB2YWx1ZSkgPT4gX3ZhcnMgPSB2YWx1ZTsKCiAgQG92ZXJyaWRlCiAgTG9nZ2VyIGdldCBsb2dnZXIgPT4gX2xvZ2dlcjsKfQoKY2xhc3MgX01vY2tMb2dnZXIgZXh0ZW5kcyBNb2NrIGltcGxlbWVudHMgTG9nZ2VyIHt9CgpjbGFzcyBfTW9ja1Byb2dyZXNzIGV4dGVuZHMgTW9jayBpbXBsZW1lbnRzIFByb2dyZXNzIHt9CgpjbGFzcyBfTW9ja1Byb2Nlc3NSZXN1bHQgZXh0ZW5kcyBNb2NrIGltcGxlbWVudHMgUHJvY2Vzc1Jlc3VsdCB7fQoKdm9pZCBtYWluKCkgewogIGdyb3VwKCdwcmVHZW4nLCAoKSB7CiAgICBsYXRlIEhvb2tDb250ZXh0IGNvbnRleHQ7CiAgICBsYXRlIExvZ2dlciBsb2dnZXI7CiAgICBsYXRlIFByb2dyZXNzIGluc3RhbGxpbmdUZXN0UnVubmVyOwoKICAgIHNldFVwKCgpIHsKICAgICAgbG9nZ2VyID0gX01vY2tMb2dnZXIoKTsKICAgICAgY29udGV4dCA9IF9GYWtlSG9va0NvbnRleHQobG9nZ2VyOiBsb2dnZXIpCiAgICAgICAgLi52YXJzID0geydydW5uZXJfcGF0aCc6ICdydW5uZXJfcGF0aCd9OwogICAgICBpbnN0YWxsaW5nVGVzdFJ1bm5lciA9IF9Nb2NrUHJvZ3Jlc3MoKTsKCiAgICAgIHdoZW4oKCkgPT4gbG9nZ2VyLnByb2dyZXNzKGFueSgpKSkudGhlblJldHVybihpbnN0YWxsaW5nVGVzdFJ1bm5lcik7CiAgICB9KTsKCiAgICB0ZXN0KCdydW4gY29tcGxldGVzJywgKCkgewogICAgICBleHBlY3QocnVuKGNvbnRleHQpLCBjb21wbGV0ZXMpOwogICAgfSk7CgogICAgdGVzdCgnaW5zdGFsbHMgZmx1dHRpdW1fdGVzdF9ydW5uZXIgY29ycmVjdGx5JywgKCkgYXN5bmMgewogICAgICB2YXIgcHJvY2Vzc1J1bm5lckNhbGxDb3VudCA9IDA7CgogICAgICBmaW5hbCByZXN1bHQgPSBfTW9ja1Byb2Nlc3NSZXN1bHQoKTsKICAgICAgYXdhaXQgcHJlR2VuKAogICAgICAgIGNvbnRleHQsCiAgICAgICAgcnVuUHJvY2VzczogKAogICAgICAgICAgZXhlY3V0YWJsZSwKICAgICAgICAgIGFyZ3MsIHsKICAgICAgICAgIFN0cmluZz8gd29ya2luZ0RpcmVjdG9yeSwKICAgICAgICAgIGJvb2w/IHJ1bkluU2hlbGwsCiAgICAgICAgfSkgYXN5bmMgewogICAgICAgICAgcHJvY2Vzc1J1bm5lckNhbGxDb3VudCsrOwogICAgICAgICAgZXhwZWN0KGV4ZWN1dGFibGUsIGVxdWFscygnZmx1dHRlcicpKTsKICAgICAgICAgIGV4cGVjdCh3b3JraW5nRGlyZWN0b3J5LCBlcXVhbHMoRGlyZWN0b3J5LmN1cnJlbnQucGF0aCkpOwogICAgICAgICAgZXhwZWN0KHJ1bkluU2hlbGwsIGlzVHJ1ZSk7CgogICAgICAgICAgaWYgKHByb2Nlc3NSdW5uZXJDYWxsQ291bnQgPT0gMSkgewogICAgICAgICAgICBleHBlY3QoYXJncywgZXF1YWxzKFsncHViJywgJ3JlbW92ZScsICdmbHV0dGl1bV90ZXN0X3J1bm5lciddKSk7CiAgICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBleHBlY3QoCiAgICAgICAgICAgICAgYXJncywKICAgICAgICAgICAgICBlcXVhbHMoWwogICAgICAgICAgICAgICAgJ3B1YicsCiAgICAgICAgICAgICAgICAnYWRkJywKICAgICAgICAgICAgICAgICdmbHV0dGl1bV90ZXN0X3J1bm5lcicsCiAgICAgICAgICAgICAgICAnLS1kZXYnLAogICAgICAgICAgICAgICAgJy0tcGF0aCcsCiAgICAgICAgICAgICAgICAncnVubmVyX3BhdGgnLAogICAgICAgICAgICAgIF0pLAogICAgICAgICAgICApOwogICAgICAgICAgfQogICAgICAgICAgcmV0dXJuIHJlc3VsdDsKICAgICAgICB9LAogICAgICApOwoKICAgICAgZXhwZWN0KHByb2Nlc3NSdW5uZXJDYWxsQ291bnQsIGVxdWFscygyKSk7CiAgICAgIHZlcmlmeSgKICAgICAgICAoKSA9PiBsb2dnZXIucHJvZ3Jlc3MoYW55KHRoYXQ6IGVxdWFscygnSW5zdGFsbGluZyB0ZXN0IHJ1bm5lcicpKSksCiAgICAgICkuY2FsbGVkKDEpOwogICAgICB2ZXJpZnkoaW5zdGFsbGluZ1Rlc3RSdW5uZXIuY29tcGxldGUpLmNhbGxlZCgxKTsKICAgIH0pOwogIH0pOwp9Cg==",
      "type": "text"
    }
  ],
  "name": "fluttium_launcher",
  "description":
      "Brick for generating a file that can launch a Fluttium runner.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev.42 <0.1.0"},
  "vars": {
    "runner_id": {
      "type": "string",
      "description": "The unique ID of the runner to launch",
      "prompt": "What is the ID of the runner?"
    },
    "runner_path": {
      "type": "string",
      "description": "The path to the result of the fluttium_test_runner brick",
      "prompt":
          "What is the path to the result of the fluttium_test_runner brick?"
    },
    "project_name": {
      "type": "string",
      "description": "The name of the project",
      "prompt": "What is the name of the project?"
    },
    "main_entry": {
      "type": "string",
      "description": "The main entry point of the project",
      "prompt": "What is the main entry point of the project?"
    },
    "steps": {
      "type": "string",
      "description": "The steps of the user flow",
      "prompt": "What are the steps (encoded as a list)?"
    }
  }
});
