name: docs
description: 'Format, lint, and build the docs'

inputs:
  working-directory:
    description: 'The working directory for the docs job'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: ⚙️ Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
        cache-dependency-path: docs/yarn.lock

    - name: 📦 Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install --frozen-lockfile

    - name: ✨ Check Format
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn run format:check

    - name: 🧹 Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn run lint

    - name: 👷 Build website
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn build
