name: Local Fluttium Environment

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    
    - shell: bash
      run: export PATH="$PATH":"$HOME/.pub-cache/bin"

    - shell: bash
      run: tools/setup_local_development.sh

    - shell: bash
      run: dart pub global activate mason_cli

    - shell: bash
      run: tools/bundle_all_bricks.sh

    - shell: bash
      run: dart pub global activate --source path packages/fluttium_cli
