name: Local Fluttium Environment

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - shell: bash
      run: dart pub global activate --source path packages/fluttium_cli

    - shell: bash
      run: tools/setup_local_development.sh

