// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final fluttiumDriverBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": ".fluttium_driver.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmFzeW5jJzsKaW1wb3J0ICdkYXJ0OnVpJzsKCmltcG9ydCAncGFja2FnZTpmbHV0dGVyL2N1cGVydGluby5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvZm91bmRhdGlvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvcmVuZGVyaW5nLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlcl90ZXN0L2ZsdXR0ZXJfdGVzdC5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmludGVncmF0aW9uX3Rlc3QvaW50ZWdyYXRpb25fdGVzdC5kYXJ0JzsKCmltcG9ydCAncGFja2FnZTp7e3twcm9qZWN0TmFtZX19fS97e3ttYWluRW50cnl9fX0nIGFzIGFwcDsKCmxhdGUgSW50ZWdyYXRpb25UZXN0V2lkZ2V0c0ZsdXR0ZXJCaW5kaW5nIGJpbmRpbmc7CmxhdGUgRmx1dHRpdW1NYW5hZ2VyIG1hbmFnZXI7Cgp2b2lkIG1haW4oKSB7CiAgbWFuYWdlciA9IEZsdXR0aXVtTWFuYWdlcigpOwogIGJpbmRpbmcgPSBJbnRlZ3JhdGlvblRlc3RXaWRnZXRzRmx1dHRlckJpbmRpbmcuZW5zdXJlSW5pdGlhbGl6ZWQoKTsKCiAgdGVzdFdpZGdldHMoCiAgICAne3tmbG93RGVzY3JpcHRpb259fScsCiAgICAodGVzdGVyKSBhc3luYyB7CiAgICAgIGFwcC5tYWluKCk7CiAgICAgIGF3YWl0IHRlc3Rlci5wdW1wQW5kU2V0dGxlKCk7CiAgICAgIHt7I2Zsb3dTdGVwc319CiAgICAgIHt7e3N0ZXB9fX17ey9mbG93U3RlcHN9fQogICAgfSwKICApOwp9CgpleHRlbnNpb24gb24gV2lkZ2V0VGVzdGVyIHsKICBGaW5kZXIgX2ZpbmRCeVRleHQoU3RyaW5nIHRleHQpIHsKICAgIGZpbmFsIHJlZ2V4cCA9IFJlZ0V4cCgnXiR0ZXh0XCQnKTsKICAgIHZhciBmaW5kZXIgPSBmaW5kLmJ5U2VtYW50aWNzTGFiZWwocmVnZXhwKTsKICAgIGlmIChmaW5kZXIuZXZhbHVhdGUoKS5pc0VtcHR5KSB7CiAgICAgIGZpbmRlciA9IGZpbmQuYnlUb29sdGlwKHRleHQpOwogICAgICBpZiAoZmluZGVyLmV2YWx1YXRlKCkuaXNFbXB0eSkgewogICAgICAgIGZpbmRlciA9IGZpbmQudGV4dENvbnRhaW5pbmcocmVnZXhwKTsKICAgICAgfQogICAgfQogICAgcmV0dXJuIGZpbmRlcjsKICB9CgogIEZ1dHVyZTx2b2lkPiBleHBlY3RWaXNpYmxlKFN0cmluZyB0ZXh0KSBhc3luYyB7CiAgICBhd2FpdCBtYW5hZ2VyLnN0YXJ0KCk7CiAgICBpZiAoX2ZpbmRCeVRleHQodGV4dCkuZXZhbHVhdGUoKS5pc05vdEVtcHR5KSB7CiAgICAgIGF3YWl0IG1hbmFnZXIuZG9uZSgpOwogICAgfSBlbHNlIHsKICAgICAgYXdhaXQgbWFuYWdlci5mYWlsKCk7CiAgICB9CiAgfQoKICBGdXR1cmU8dm9pZD4gZXhwZWN0Tm90VmlzaWJsZShTdHJpbmcgdGV4dCkgYXN5bmMgewogICAgYXdhaXQgbWFuYWdlci5zdGFydCgpOwogICAgaWYgKF9maW5kQnlUZXh0KHRleHQpLmV2YWx1YXRlKCkuaXNFbXB0eSkgewogICAgICBhd2FpdCBtYW5hZ2VyLmRvbmUoKTsKICAgIH0gZWxzZSB7CiAgICAgIGF3YWl0IG1hbmFnZXIuZmFpbCgpOwogICAgfQogIH0KCiAgRnV0dXJlPHZvaWQ+IHRhcE9uKFN0cmluZyB0ZXh0KSBhc3luYyB7CiAgICBhd2FpdCBtYW5hZ2VyLnN0YXJ0KCk7CiAgICBhd2FpdCB0YXAoX2ZpbmRCeVRleHQodGV4dCkpOwogICAgYXdhaXQgcHVtcEFuZFNldHRsZSgpOwogICAgYXdhaXQgbWFuYWdlci5kb25lKCk7CiAgfQoKICBGdXR1cmU8dm9pZD4gbG9uZ1RhcE9uKFN0cmluZyB0ZXh0KSBhc3luYyB7CiAgICBhd2FpdCBtYW5hZ2VyLnN0YXJ0KCk7CiAgICBhd2FpdCBsb25nUHJlc3MoX2ZpbmRCeVRleHQodGV4dCkpOwogICAgYXdhaXQgcHVtcEFuZFNldHRsZSgpOwogICAgYXdhaXQgbWFuYWdlci5kb25lKCk7CiAgfQoKICBGdXR1cmU8dm9pZD4gdGFrZVNjcmVlbnNob3QoU3RyaW5nIG5hbWUpIGFzeW5jIHsKICAgIGF3YWl0IG1hbmFnZXIuc3RhcnQoKTsKICAgIGZpbmFsIGJvdW5kYXJ5ID0gZmlyc3RSZW5kZXJPYmplY3QoZmluZC5ieVR5cGUoUmVwYWludEJvdW5kYXJ5KSkKICAgICAgICBhcyBSZW5kZXJSZXBhaW50Qm91bmRhcnk7CiAgICBmaW5hbCBpbWFnZSA9IGF3YWl0IGJvdW5kYXJ5LnRvSW1hZ2UoKTsKICAgIGZpbmFsIGJ5dGVEYXRhID0gYXdhaXQgaW1hZ2UudG9CeXRlRGF0YShmb3JtYXQ6IEltYWdlQnl0ZUZvcm1hdC5wbmcpOwogICAgZmluYWwgcG5nQnl0ZXMgPSBieXRlRGF0YSEuYnVmZmVyLmFzVWludDhMaXN0KCk7CiAgICBhd2FpdCBtYW5hZ2VyLnNlbmQoJ3NjcmVlbnNob3QnLCBwbmdCeXRlcy5qb2luKCcsJykpOwogICAgYXdhaXQgbWFuYWdlci5kb25lKCk7CiAgfQoKICBGdXR1cmU8dm9pZD4gaW5wdXRUZXh0KFN0cmluZyB0ZXh0KSBhc3luYyB7CiAgICBhd2FpdCBtYW5hZ2VyLnN0YXJ0KCk7CiAgICB2YXIgY2hhcnMgPSBbXTsKICAgIGZvciAoZmluYWwgY2hhciBpbiB0ZXh0LnNwbGl0KCcnKSkgewogICAgICBjaGFycy5hZGQoY2hhcik7CiAgICAgIHRlc3RUZXh0SW5wdXQuZW50ZXJUZXh0KGNoYXJzLmpvaW4oKSk7CiAgICAgIGF3YWl0IHB1bXBBbmRTZXR0bGUoKTsKICAgIH0KICAgIGF3YWl0IG1hbmFnZXIuZG9uZSgpOwogIH0KfQoKY2xhc3MgRmx1dHRpdW1NYW5hZ2VyIHsKICBib29sIF9oYXNGYWlsZWQgPSBmYWxzZTsKCiAgRnV0dXJlPHZvaWQ+IHN0YXJ0KCkgPT4gc2VuZCgnc3RhcnQnKTsKCiAgRnV0dXJlPHZvaWQ+IGRvbmUoKSA9PiBzZW5kKCdkb25lJyk7CgogIEZ1dHVyZTx2b2lkPiBmYWlsKCkgYXN5bmMgewogICAgYXdhaXQgc2VuZCgnZmFpbCcpOwogICAgX2hhc0ZhaWxlZCA9IHRydWU7IAogIH0KCiAgRnV0dXJlPHZvaWQ+IHNlbmQoU3RyaW5nIGFjdGlvbiwgW09iamVjdD8gZGF0YV0pIGFzeW5jIHsKICAgIGlmIChfaGFzRmFpbGVkKSB7CiAgICAgIHJldHVybiBDb21wbGV0ZXIoKS5mdXR1cmU7CiAgICB9CiAgICBmaW5hbCBtZXNzYWdlID0gJ2ZsdXR0aXVtOiRhY3Rpb246JGRhdGE7JzsKCiAgICBmaW5hbCBtYXhMZW5ndGggPSA4MDA7CiAgICBmb3IgKGludCBpID0gMDsgaSA8IG1lc3NhZ2UubGVuZ3RoOyBpICs9IG1heExlbmd0aCkgewogICAgICBpbnQgb2Zmc2V0ID0gaSArIG1heExlbmd0aDsKICAgICAgZmluYWwgcGllY2UgPSBtZXNzYWdlLnN1YnN0cmluZyhpLCBvZmZzZXQgPj0gbWVzc2FnZS5sZW5ndGggPyBtZXNzYWdlLmxlbmd0aCA6IG9mZnNldCk7CiAgICAgIGRlYnVnUHJpbnQocGllY2UpOwogICAgfQogIH0KfQ==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "fluttium_driver",
  "description": "The driver that runs the Fluttium Flow.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev.26 <0.1.0"},
  "vars": {
    "projectName": {
      "type": "string",
      "description": "The project name",
      "prompt": "What is the project name?"
    },
    "flowDescription": {
      "type": "string",
      "description": "The flow description",
      "prompt": "What is the flow description?"
    },
    "flowSteps": {
      "type": "string",
      "description": "The flow steps",
      "prompt": "What are the flow steps (encoded as a list)?"
    }
  }
});
