name: fluttium_protocol
description: The protocol for the communication between the runner and the driver of Fluttium
version: 0.1.0-dev.1
homepage: https://fluttium.dev
repository: https://github.com/wolfenrain/fluttium
issue_tracker: https://github.com/wolfenrain/fluttium/issues
documentation: https://fluttium.dev/docs/why-fluttium

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  meta: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0
