name: fluttium_interfaces
description: The interfaces and definitions used by the Fluttium user flow testing framework
homepage: https://fluttium.dev
repository: https://github.com/wolfenrain/fluttium
version: 0.1.0-dev.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  pub_semver: ^2.1.2
  yaml: ^3.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
